### ISSUE TITLE
获取头像

### ISSUE THREAD

**Issue by zhengshengjie666** [karthikeyan-krishna/JavsApp#2]
public void loadProfilePicThumb(String jId) {
        String tag = WhatsAppUtil.getMessageTag();
        ws.sendText(tag+",,"+"[\"query\", \"ProfilePicThumb\", \"8613xxxxxxx@c.us\"]");
    }
otherError  jid=861xxxxxxxx json = {"eurl":"xxxxxxxxxxxxxxxx","tag":"xxxxx"}

**Comment by karthikeyan-krishna** [comment]
I don't understand the issue

**Comment by zhengshengjie666** [comment]
我只是做了一个记录，这不是一个问题。
执行ws.sendText(tag+",,"+"["query", "ProfilePicThumb", "8613xxxxxxx@c.us"]"); 可以获取头像

**Comment by karthikeyan-krishna** [comment]
Thank you so much. @zhengshengjie666
